# Module manifest for module 'Module.Required.Functions'
# Generated by: Van Phuong Thanh
# Generated on: 5/08/2021

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Module.Required.Functions.psm1'

    # Version number of this module.
    ModuleVersion = '1.0'

    # ID used to uniquely identify this module
    GUID = 'dadea276-ae04-4c01-b901-06838167ec7c'

    # Author of this module
    Author = 'Van Phuong Thanh'

    # Company or vendor of this module
    CompanyName = 'Invididual'

    # Copyright statement for this module
    Copyright = '(c) 2021 Van Phuong Thanh. All rights reserved.'

    # Description of the functionality provided by this module
    # Description = ''

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

}